name: Build iOS

on:
  push:
    branches:
      - main  # 你想要触发构建的分支
  pull_request:
    branches:
      - main  # 你想要触发构建的分支

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # 替换为你实际使用的 Flutter 版本

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS App
        run: |
          flutter build ios --release

      - name: Archive iOS App
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/build/Runner.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Runner.xcarchive -exportPath ${{ github.workspace }}/build -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: MyFlutterApp.ipa
          path: build/*.ipa