name: Build iOS

on:
  push:
    branches:
      - main  # 你想要触发构建的分支
  pull_request:
    branches:
      - main  # 你想要触发构建的分支

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          # sudo gem install fastlane

   
      - name: Check out repository
        uses: actions/checkout@v3
      

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 根据你的项目要求选择 Ruby 版本
    
          
      - name: Install Fastlane
        run: gem install fastlane

      - name: Sync certificates
        env:
          MATCH_PASSWORD: 123456  # 在 GitHub Secrets 中设置 MATCH_PASSWORD
        run: fastlane match development  # 或者使用 production
      
      # - name: Install dependencies
      #   run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod init
          pod install
          
      - name: Build iOS App
        run: fastlane build

      # - name: Archive iOS App
      #   run: |
      #     cd ios
      #     xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/build/Runner.xcarchive

      # - name: Export IPA
      #   run: |
      #     xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Runner.xcarchive -exportPath ${{ github.workspace }}/build -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: MyFlutterApp.ipa
          path: ios/build/*.ipa